version: '3'

services:
  n8n:
    build:
      context: .
      args:
        N8N_VERSION: ${N8N_VERSION:-latest}
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      # Add any other environment variables you need
    volumes:
      - ./n8n_data:/home/node/.n8n
